from Portrait.pages.cart_page import CartPage
import time

def test_sale(driver):
    page = CartPage(driver)
    page.find_element_from_list_cart_menu("Go to Menu")
    time.sleep(2)
    page.to_open_bottles_cat()
    time.sleep(2)
    page.to_add_glass_cat()
    time.sleep(2)
    page.to_add()
    time.sleep(2)
    page.go_checkout()
    time.sleep(2)
    page.gift()
    time.sleep(1)

def test_sale1(driver):
    page = CartPage(driver)
    page.find_element_from_list_cart_menu("Go to Menu")
    time.sleep(2)
    page.to_open_bottles_cat()
    time.sleep(2)
    page.to_add_glass_cat()
    time.sleep(2)
    page.to_add()
    time.sleep(2)
    page.go_checkout()
    time.sleep(2)
    page.gift()
    time.sleep(1)

def test_sale2(driver):
    page = CartPage(driver)
    page.find_element_from_list_cart_menu("Go to Menu")
    time.sleep(2)
    page.to_open_bottles_cat()
    time.sleep(2)
    page.to_add_glass_cat()
    time.sleep(2)
    page.to_add()
    time.sleep(2)
    page.go_checkout()
    time.sleep(2)
    page.gift()
    time.sleep(1)


def test_sale3(driver):
    page = CartPage(driver)
    page.find_element_from_list_cart_menu("Go to Menu")
    time.sleep(2)
    page.to_open_bottles_cat()
    time.sleep(2)
    page.to_add_glass_cat()
    time.sleep(2)
    page.to_add()
    time.sleep(2)
    page.go_checkout()
    time.sleep(2)
    page.gift()
    time.sleep(1)


def test_sale4(driver):
    page = CartPage(driver)
    page.find_element_from_list_cart_menu("Go to Menu")
    time.sleep(2)
    page.to_open_bottles_cat()
    time.sleep(2)
    page.to_add_glass_cat()
    time.sleep(2)
    page.to_add()
    time.sleep(2)
    page.go_checkout()
    time.sleep(2)
    page.gift()
    time.sleep(1)


def test_sale5(driver):
    page = CartPage(driver)
    page.find_element_from_list_cart_menu("Go to Menu")
    time.sleep(2)
    page.to_open_bottles_cat()
    time.sleep(2)
    page.to_add_glass_cat()
    time.sleep(2)
    page.to_add()
    time.sleep(2)
    page.go_checkout()
    time.sleep(2)
    page.gift()
    time.sleep(1)


def test_sale6(driver):
    page = CartPage(driver)
    page.find_element_from_list_cart_menu("Go to Menu")
    time.sleep(2)
    page.to_open_bottles_cat()
    time.sleep(2)
    page.to_add_glass_cat()
    time.sleep(2)
    page.to_add()
    time.sleep(2)
    page.go_checkout()
    time.sleep(2)
    page.gift()
    time.sleep(1)


def test_sale7(driver):
    page = CartPage(driver)
    page.find_element_from_list_cart_menu("Go to Menu")
    time.sleep(2)
    page.to_open_bottles_cat()
    time.sleep(2)
    page.to_add_glass_cat()
    time.sleep(2)
    page.to_add()
    time.sleep(2)
    page.go_checkout()
    time.sleep(2)
    page.gift()
    time.sleep(1)


def test_sale8(driver):
    page = CartPage(driver)
    page.find_element_from_list_cart_menu("Go to Menu")
    time.sleep(2)
    page.to_open_bottles_cat()
    time.sleep(2)
    page.to_add_glass_cat()
    time.sleep(2)
    page.to_add()
    time.sleep(2)
    page.go_checkout()
    time.sleep(2)
    page.gift()
    time.sleep(1)


def test_sale9(driver):
    page = CartPage(driver)
    page.find_element_from_list_cart_menu("Go to Menu")
    time.sleep(2)
    page.to_open_bottles_cat()
    time.sleep(2)
    page.to_add_glass_cat()
    time.sleep(2)
    page.to_add()
    time.sleep(2)
    page.go_checkout()
    time.sleep(2)
    page.gift()
    time.sleep(1)


def test_sale10(driver):
    page = CartPage(driver)
    page.find_element_from_list_cart_menu("Go to Menu")
    time.sleep(2)
    page.to_open_bottles_cat()
    time.sleep(2)
    page.to_add_glass_cat()
    time.sleep(2)
    page.to_add()
    time.sleep(2)
    page.go_checkout()
    time.sleep(2)
    page.gift()
    time.sleep(1)


def test_sale11(driver):
    page = CartPage(driver)
    page.find_element_from_list_cart_menu("Go to Menu")
    time.sleep(2)
    page.to_open_bottles_cat()
    time.sleep(2)
    page.to_add_glass_cat()
    time.sleep(2)
    page.to_add()
    time.sleep(2)
    page.go_checkout()
    time.sleep(2)
    page.gift()
    time.sleep(1)