from Android.Landscape.pages.settings_inventory_page import InventoryPage
import time

#Проверка наличия элемента "Items"
def test_is_element_present_items(driver):
    page = InventoryPage(driver)
    page.is_element_present_items()

def test_create_item(driver):
    page = InventoryPage(driver)
    page.press_button_items()
    page.press_button_create_item()
    time.sleep(1)
    page.name_input("Create_item")
    page.price_input("5025")
    page.cost_input("2000")
    page.barcode_input("456789")
    page.press_button_choose_category()
    time.sleep(1)
    page.search_option("Category for item create")
    time.sleep(1)
    page.find_element_from_list_name("Category for item create")
    page.press_button_save()

def test_select_printer_type(driver):
    page = InventoryPage(driver)
    page.press_button_items()
    page.search_option("Create_item")
    time.sleep(1)
    page.find_element_from_list_name("Create_item")
    time.sleep(1)
    page.press_button_printer_type()
    time.sleep(1)
    page.find_element_from_list_name("Bar")
    page.press_button_save()

def test_select_image(driver):
    page = InventoryPage(driver)
    page.press_button_items()
    page.search_option("Create_item")
    time.sleep(1)
    page.find_element_from_list_name("Create_item")
    time.sleep(1)
    page.scroll(406, 620, 406, 336)
    page.press_button_image()
    time.sleep(1)
    page.press_button_gallery()
    time.sleep(1)
    page.press_button_pictures()
    time.sleep(1)
    page.select_picture()
    time.sleep(1)
    page.press_button_save()

def test_select_modifier(driver):
    page = InventoryPage(driver)
    page.press_button_items()
    page.search_option("Create_item")
    time.sleep(1)
    page.find_element_from_list_name("Create_item")
    time.sleep(1)
    page.press_button_modifiers_item()
    time.sleep(1)
    page.find_element_from_list_name('Mod_for_test_01')
    time.sleep(1)
    page.press_button_confirm()
    time.sleep(1)
    page.scroll(406, 620, 406, 133)
    page.modifier_check("MOD_FOR_TEST_01")
    time.sleep(1)
    page.press_button_save()

def test_select_discount(driver):
    page = InventoryPage(driver)
    page.press_button_items()
    page.search_option("Create_item")
    time.sleep(1)
    page.find_element_from_list_name("Create_item")
    time.sleep(1)
    page.press_button_discounts_item()
    page.find_element_from_list_name('Discount_for_test_01')
    time.sleep(1)
    page.press_button_confirm()
    time.sleep(1)
    page.scroll(406, 620, 406, 133)
    page.discount_check("22.00%")
    time.sleep(1)
    page.press_button_save()

def test_created_item(driver):
    page = InventoryPage(driver)
    page.press_button_save()
    time.sleep(10)
    page.press_button_items()
    page.search_option("Create_item")
    time.sleep(1)
    page.find_element_from_list_name("Create_item")
